### ISSUE TITLE
Дарожная мапа распрацоўкі (абноўлена 9.5.2020)

### ISSUE THREAD

**Issue by rizomaa** [konstbel/landing#13]
Прывітанне!

Вы знаёміцеся з дарожнай мапай развіцця праекта Лэндынг для сайта канстутуцыя.бел. 

Гэты двіж задуманы каб у супрацы з айці-валанцёрамі (праграмістамі, дызайнерамі, маркетолагамі) **зрабіць зручную і прывабную пляцоўку** грамадскай кампаніі Свежы Вецер (сайт: канстытуцыя.бел). 

**Як вынік,** наведвальнікам сайта становіцца зручней атрымліваць інфармацыю пра дзейнасць, далучацца да працы каманды.

Перад далучэннем раім пазнаёміцца з нашымі падыходамі.

Што зараз найбольш актуальна

1.1 - пажаданы час запуска **22 лютага**
- [x] [Галоўная старонка](https://github.com/konstbel/landing/issues/20) +
- [x] Старонак [апісання Пра нас](https://github.com/konstbel/landing/issues/17). +
- [x] Старонка [Як далучыцца](https://github.com/konstbel/landing/issues/17)
- [x] [Распрацоўка брэндбука](https://github.com/konstbel/landing/issues/19).
**Патрэбны:** вэб-дызайнеры, капірайтэры (кантэнт: тэкст і фота), вярстальшчык, дэйплоймэнт.

1.2. - пажаданы час запуска **7 сакавіка.**

- [x] [Блог](https://github.com/konstbel/landing/issues/21) - эпік|

**Патрэбны:** фрондэнд і бэкэнд распрацўшчык, капірайтэрыя (аўтары тэкстаў)

1.3. - Рассыльшчык. Неабходны час запуска **10 чэрвеня**

- [ ] [Рассылка](https://github.com/konstbel/landing/issues/7) - эпік|
- [ ] Рэалізаваць дакументацыю - [Адмінка](https://github.com/konstbel/landing/issues/51) + [Статыка](https://github.com/konstbel/landing/issues/49)  - 20 траўня (мая) 
- [ ] Запусціць бэкэнд ([мэйл рассылка](https://github.com/konstbel/landing/issues/47)) - 15 траўня
- [ ] Запусціць бэкэнд ([пуш паведамленняў](https://github.com/konstbel/landing/issues/48)) - 5 чэрвеня
- [ ] Далучыць фронтэнд для адмінкі. - 25 траўня
- [ ] Рэалізаваць падпіскі ([мэйл](https://github.com/konstbel/landing/issues/43) + [пуш](https://github.com/konstbel/landing/issues/46)) з боку карыстальнікаў сайта - 5 чэрвеня.

1.4. [Апісаць дэплоймэнт](https://github.com/konstbel/landing/issues/14)  - 10 чэвеня

**Патрэбны:** бэкэнд распрацўшчык, спецыяліст па працы з API, трохі фронт энд распрацоўшчык

**Comment by rizomaa** [comment]
Абноўлена дарожная мапа пункты 1.3 і 1.4
