### ISSUE TITLE
Наведение порядка

### ISSUE THREAD

**Issue by alherd-by** [konstbel/landing#85]
- [x] ~~выделить все файлы в отдельный неймспейс landing. Отредактировать конфиги netlify и forestry~~ Слишком много затруднений возникает со сторонними сервисами #87 
- [x] сделать тему alherd темой по умолчанию - вынести из themes в корень #88 
- [x] зафиксировать версию hugo и указать в вики #90
